import type { Locale } from "@/lib/i18n/config";

const en = { privacy: "Privacy", terms: "Website terms", selection: "Selection guidance", copyright: "All rights reserved.", quote: "Request a quote", inquiries: "Inquiry list", details: "Specifications", compare: "Compare models", questions: "Questions before you choose", technical: "Technical information", contactIntro: "Send a model, a replacement reference or your application requirements.", emailDraft: "Prepare your inquiry", englishContent: "This document is currently available in English.", dataNotice: "We use the information you provide to respond to your inquiry.", localDraft: "This shortlist is saved in this browser. It has not been sent to our team.", preparing: "Preparing…", next: "Next", previous: "Previous", unknown: "Not specified", cookieSettings: "Cookie settings", analyticsText: "Allow optional analytics to help us understand how this website is used? Product browsing and sizing work without it.", allow: "Allow analytics", reject: "Essential only" };
type Copy = { [K in keyof typeof en]: string };
const copies: Record<Locale, Copy> = {
  en,
  "zh-cn": { privacy: "隐私说明", terms: "网站使用条款", selection: "选型使用说明", copyright: "保留所有权利。", quote: "获取报价", inquiries: "询盘清单", details: "技术参数", compare: "型号对比", questions: "选型前的常见问题", technical: "技术信息", contactIntro: "提供产品型号、替换件参考或应用要求，我们将协助确认。", emailDraft: "准备询盘", englishContent: "此文档当前以英文提供。", dataNotice: "我们使用你提供的信息回复本次询盘。", localDraft: "此清单保存在当前浏览器中，尚未发送给我们的团队。", preparing: "处理中…", next: "下一页", previous: "上一页", unknown: "未提供", cookieSettings: "Cookie 设置", analyticsText: "是否允许可选访问分析，帮助我们了解网站使用情况？不影响产品浏览和选型。", allow: "允许访问分析", reject: "仅必要功能" },
  de: { ...en, privacy: "Datenschutz", terms: "Nutzungsbedingungen", selection: "Auslegungshinweise", copyright: "Alle Rechte vorbehalten.", quote: "Angebot anfragen", inquiries: "Anfrageliste", details: "Technische Daten", compare: "Modelle vergleichen", questions: "Fragen zur Auswahl", technical: "Technische Informationen", contactIntro: "Senden Sie ein Modell, eine Ersatzteilreferenz oder Ihre Anwendungsanforderungen.", emailDraft: "Anfrage vorbereiten", englishContent: "Dieses Dokument ist derzeit auf Englisch verfügbar.", dataNotice: "Wir verwenden Ihre Angaben zur Bearbeitung Ihrer Anfrage.", localDraft: "Diese Liste ist in diesem Browser gespeichert und wurde noch nicht an unser Team gesendet.", next: "Weiter", previous: "Zurück", unknown: "Nicht angegeben", cookieSettings: "Cookie-Einstellungen", analyticsText: "Optionale Nutzungsanalyse erlauben? Produktkatalog und Auslegung funktionieren auch ohne Analyse.", allow: "Analyse erlauben", reject: "Nur erforderlich" },
  fr: { ...en, privacy: "Confidentialité", terms: "Conditions d'utilisation", selection: "Conseils de dimensionnement", copyright: "Tous droits réservés.", quote: "Demander un devis", inquiries: "Liste de demande", details: "Caractéristiques", compare: "Comparer les modèles", questions: "Questions avant de choisir", technical: "Informations techniques", contactIntro: "Envoyez un modèle, une référence à remplacer ou vos besoins d'application.", emailDraft: "Préparer votre demande", englishContent: "Ce document est actuellement disponible en anglais.", dataNotice: "Nous utilisons vos informations pour répondre à votre demande.", localDraft: "Cette liste est enregistrée dans ce navigateur et n'a pas encore été envoyée à notre équipe.", next: "Suivant", previous: "Précédent", unknown: "Non renseigné", cookieSettings: "Paramètres des cookies", analyticsText: "Autoriser l'analyse facultative de l'utilisation ? Le catalogue et le dimensionnement fonctionnent sans celle-ci.", allow: "Autoriser l'analyse", reject: "Nécessaires uniquement" },
  it: { ...en, privacy: "Privacy", terms: "Condizioni d'uso", selection: "Guida al dimensionamento", copyright: "Tutti i diritti riservati.", quote: "Richiedi un preventivo", inquiries: "Lista richieste", details: "Specifiche", compare: "Confronta modelli", questions: "Domande per la selezione", technical: "Informazioni tecniche", contactIntro: "Inviaci un modello, un riferimento da sostituire o i requisiti della tua applicazione.", emailDraft: "Prepara la richiesta", englishContent: "Questo documento è attualmente disponibile in inglese.", dataNotice: "Utilizziamo le informazioni fornite per rispondere alla richiesta.", localDraft: "Questa lista è salvata nel browser e non è ancora stata inviata al nostro team.", next: "Successivo", previous: "Precedente", unknown: "Non specificato", cookieSettings: "Impostazioni cookie", analyticsText: "Consentire l'analisi facoltativa dell'utilizzo? Catalogo e dimensionamento funzionano anche senza.", allow: "Consenti analisi", reject: "Solo necessari" },
};
export const getSiteUiCopy = (locale: Locale) => copies[locale];
